server:
  port: 8888

app:
  version: v1.1.0
  store:
    path: /tmp/imageserver
spring:
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    cn.geobeans: debug